name: Freedom
favicon: null
layout_spectrum: 0.20455989544279873
typography_spectrum: 0.44924029731191695
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7454659519717097
  lightness: 0.6390369941946119
  saturation: 0.7866578388493508
  rhythmicContrast: 0.504357369383797
purpose: []
